
version: "3.7"

services:

  bokehapp:
    build: ./bokeh_visualization
    container_name: bokeh
    restart: always
    ports:
      - '5006:5006'

  flaskapp:
    build: ./flask
    container_name: flask
    restart: always
    ports:
      - '80:5000'
    depends_on:
        - bokehapp
    
